version: "3.9"

services:
  api:
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    container_name: db
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./data:/var/lib/mysql
#      - "./var/mysql:/var/lib/mysql"
#      - "./ops/database:/docker-entrypoint-initdb.d"
#      - "./var/log/mysql:/var/log/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", '-u', 'user', '-p password' ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      db:
        condition: service_healthy